name: livetable-db
services:
  mysql:
    build: .
    container_name: livetable-mysql
    ports:
      - "58923:58923"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: livetable
      MYSQL_USER: livetable
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
